# Generated by Django 3.2.6 on 2021-08-29 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regatta', '0004_auto_20210829_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='regatta',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 29)),
            preserve_default=False,
        ),
    ]
