# Generated by Django 3.2.6 on 2021-08-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regatta', '0005_regatta_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200, null=True)),
                ('regatta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regatta.regatta')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=30, null=True)),
                ('start_time', models.DateTimeField()),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regatta.clazz')),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('end_time', models.DateTimeField()),
                ('racing_time', models.IntegerField()),
                ('handicap_time', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regatta.race')),
            ],
        ),
        migrations.CreateModel(
            name='RaceBoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sail_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('finrating', models.DecimalField(decimal_places=4, max_digits=5)),
                ('boat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regatta.boat')),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regatta.clazz')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regatta.club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
