# Generated by Django 3.2.6 on 2021-08-29 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('regatta', '0006_clazz_race_raceboat_raceresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='boat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regatta.boat'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regatta.club'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='finrating',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceresult',
            name='model',
            field=models.CharField(default='Guy 22', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceresult',
            name='name',
            field=models.CharField(default='Sympa', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raceresult',
            name='sail_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RaceBoat',
        ),
    ]
